commands:
- genus -no_gui -f START.tcl -log logs/genus.log
- mkdir -p outputs && cd outputs
- ln -sf ../results_syn/syn_out.v design.v
- ln -sf ../results_syn/syn_out._default_constraint_mode_.sdc design.sdc
- ln -sf ../results_syn/syn_out.sdf design.sdf
- ln -sf ../results_syn/syn_out.spef design.spef
- ln -sf ../name_map.rpt design.namemap
debug:
- genus -no_gui -f results_syn/syn_out.genus_setup.tcl
inputs:
- 1_ADD_16b.sv
- 2_ADD_16_flopped.sv
- adk
- constraints.tcl
name: cadence-genus-synthesis
outputs:
- design.v
- design.sdc
- design.sdf
- design.spef
- design.namemap
parameters:
  clock_period: 1.0
  design_name: undefined
  flatten_effort: 1
  gate_clock: true
  order:
  - designer-interface.tcl
  - setup-session.tcl
  - read-design.tcl
  - constraints.tcl
  - compile.tcl
  - generate-results.tcl
  read_hdl_defines: ''
  uniquify_with_design_name: true
postconditions:
- assert File( 'outputs/design.v' )
- assert File( 'outputs/design.sdc' )
- assert File( 'outputs/design.sdf' )
- assert File( 'outputs/design.spef' )
- assert 'Cannot resolve reference' not in File( 'logs/genus.log' )
- assert 'Error   :' not in File( 'logs/genus.log' )
- assert 'create_clock' in File( 'outputs/design.sdc' )
preconditions:
- assert Tool( 'genus' )
- assert File( 'inputs/1_ADD_16b.sv' )
- assert File( 'inputs/2_ADD_16_flopped.sv' )
- assert File( 'inputs/adk' )
- assert File( 'inputs/constraints.tcl' )
